DROP DATABASE IF EXISTS laligaea;
CREATE DATABASE IF NOT EXISTS laligaea;

USE laligaea;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS clubes;
CREATE TABLE IF NOT EXISTS clubes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    ciudad VARCHAR(255) NOT NULL,
    estadio VARCHAR(255) NOT NULL,
    fundacion INT NOT NULL,
    presidente VARCHAR(255) NOT NULL,
    entrenador VARCHAR(255) NOT NULL,
    escudo VARCHAR(255) NOT NULL,
    add_fast BOOLEAN NOT NULL DEFAULT FALSE
);

